version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.2.0
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:3.2.0
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_PORT=8081
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-network

  jupyter:
    image: jupyter/pyspark-notebook
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    networks:
      - spark-network
    depends_on:
      - spark-master

  # Spark-submit service
  spark-submit:
    image: bitnami/spark:3.2.0
    command: /opt/bitnami/spark/bin/spark-submit --master spark://spark-master:7077 /app/project.py
    volumes:
      - .:/app
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
